name: 安装musl
run-name: 安装musl
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 安装musl-cross-make
        run: |
          git clone https://github.com/richfelker/musl-cross-make.git
          cd musl-cross-make
          ls
          make TARGET=x86_64-linux-musl
          make install