name: 安装musl
run-name: 安装musl
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: git clone https://github.com/richfelker/musl-cross-make.git
      - run: |
          cd musl-cross-make
          ./make
